"use client";

import { useCallback, useEffect, useState } from "react";
import { useApp } from "@/components/app-provider";
import { createV2Department, createV2Staff, listV2Departments, listV2Staff, setV2DepartmentState, updateV2Department, updateV2Staff, type V2Department, type V2Staff } from "@/lib/admin-v2-foundation";
import { getV2DepartmentLabel } from "@/lib/v2-contracts";

const copy = { en: { title: "Version 2 department and Staff foundation", departments: "Departments", staff: "Staff profiles", create: "Create", save: "Save", archive: "Archive", reactivate: "Reactivate", name: "English name", myName: "Myanmar name", description: "Description", employee: "Employee code", display: "Display name", email: "Work email", position: "Position", shift: "Shift", capacity: "Capacity", state: "Employment state", department: "Primary department", languages: "Languages (en,my)", saved: "Saved", error: "Could not save changes." }, my: { title: "Version ၂ ဌာနနှင့် ဝန်ထမ်းအခြေခံ", departments: "ဌာနများ", staff: "ဝန်ထမ်းပရိုဖိုင်များ", create: "ဖန်တီးရန်", save: "သိမ်းရန်", archive: "သိမ်းဆည်းရန်", reactivate: "ပြန်လည်အသက်သွင်းရန်", name: "အင်္ဂလိပ်အမည်", myName: "မြန်မာအမည်", description: "ဖော်ပြချက်", employee: "ဝန်ထမ်းကုဒ်", display: "အမည်", email: "အလုပ်အီးမေးလ်", position: "ရာထူး", shift: "အလုပ်ချိန်", capacity: "တာဝန်ခံနိုင်မှု", state: "အလုပ်အခြေအနေ", department: "အဓိကဌာန", languages: "ဘာသာစကား (en,my)", saved: "သိမ်းပြီးပါပြီ", error: "သိမ်းဆည်း၍ မရပါ။" } } as const;
const key = () => globalThis.crypto?.randomUUID?.() ?? `phase2-${Date.now()}`;

export function AdminV2Foundation() {
  const { locale } = useApp();
  const text = copy[locale === "my" ? "my" : "en"];
  const [departments, setDepartments] = useState<V2Department[]>([]);
  const [staff, setStaff] = useState<V2Staff[]>([]);
  const [message, setMessage] = useState("");
  const [departmentForm, setDepartmentForm] = useState({ departmentId: "general_complaints", nameEn: "Customer Complaint Unit", nameMy: "ဖောက်သည်တိုင်ကြားမှုဌာန", description: "Fallback complaint workspace", defaultStaffCapacity: "10" });
  const [staffForm, setStaffForm] = useState({ employeeCode: "", displayName: "", workEmail: "", position: "", shift: "day", capacity: "5", departmentId: "general_complaints" });
  const refresh = useCallback(async () => { try { const [departmentPage, staffPage] = await Promise.all([listV2Departments(), listV2Staff()]); setDepartments(departmentPage.departments ?? []); setStaff(staffPage.staff ?? []); } catch { setMessage(text.error); } }, [text.error]);
  // The initial request synchronizes the Admin view with the trusted API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void refresh(); }, [refresh]);
  async function createDepartment(event: React.FormEvent) { event.preventDefault(); try { await createV2Department({ departmentId: departmentForm.departmentId, nameEn: departmentForm.nameEn, nameMy: departmentForm.nameMy, description: departmentForm.description, isCustomerComplaintUnit: departmentForm.departmentId === "general_complaints", routingEnabled: true, assignmentPolicy: { strategy: "priority_then_workload", languagePreference: true, allowManualClaim: false }, defaultStaffCapacity: Number(departmentForm.defaultStaffCapacity), idempotencyKey: key() }); setMessage(text.saved); await refresh(); } catch { setMessage(text.error); } }
  async function createStaff(event: React.FormEvent) { event.preventDefault(); try { await createV2Staff({ employeeCode: staffForm.employeeCode, displayName: staffForm.displayName, workEmail: staffForm.workEmail, departmentIds: [staffForm.departmentId], primaryDepartmentId: staffForm.departmentId, position: staffForm.position, employmentState: "invited", availabilityState: "offline", capacity: Number(staffForm.capacity), languageSkills: ["en", "my"], shift: staffForm.shift, idempotencyKey: key() }); setMessage(text.saved); await refresh(); } catch { setMessage(text.error); } }
  async function editDepartment(department: V2Department) { try { await updateV2Department(department.departmentId, { nameEn: department.nameEn, nameMy: department.nameMy, description: department.description, routingEnabled: department.routingEnabled, assignmentPolicy: department.assignmentPolicy, defaultStaffCapacity: department.defaultStaffCapacity, idempotencyKey: key() }); setMessage(text.saved); await refresh(); } catch { setMessage(text.error); } }
  async function editStaff(person: V2Staff) { try { await updateV2Staff(person.staffId, { displayName: person.displayName, workEmail: person.workEmail, departmentIds: person.departmentIds, primaryDepartmentId: person.primaryDepartmentId, position: person.position, employmentState: person.employmentState, availabilityState: person.availabilityState, capacity: person.capacity, activeWorkload: person.activeWorkload, languageSkills: person.languageSkills, shift: person.shift, loginEnabled: person.loginEnabled, idempotencyKey: key() }); setMessage(text.saved); await refresh(); } catch { setMessage(text.error); } }
  return <section aria-labelledby="v2-foundation-heading" className="admin-panel"><h2 id="v2-foundation-heading">{text.title}</h2>{message ? <p role="status">{message}</p> : null}<div className="admin-grid"><div><h3>{text.departments}</h3><form onSubmit={createDepartment}><input aria-label={text.name} value={departmentForm.nameEn} onChange={(event) => setDepartmentForm({ ...departmentForm, nameEn: event.target.value })} placeholder={text.name} required /><input aria-label={text.myName} value={departmentForm.nameMy} onChange={(event) => setDepartmentForm({ ...departmentForm, nameMy: event.target.value })} placeholder={text.myName} required /><input aria-label={text.description} value={departmentForm.description} onChange={(event) => setDepartmentForm({ ...departmentForm, description: event.target.value })} placeholder={text.description} required /><button type="submit">{text.create}</button></form>{departments.map((department) => <article key={department.departmentId}><strong>{getV2DepartmentLabel(department.departmentId, locale === "my" ? "my" : "en")}</strong> — {locale === "my" ? department.nameMy : department.nameEn}<button type="button" onClick={() => void editDepartment(department)}>{text.save}</button><button type="button" onClick={() => void setV2DepartmentState(department.departmentId, department.state === "active" ? "archived" : "active", key()).then(refresh)}>{department.state === "active" ? text.archive : text.reactivate}</button></article>)}</div><div><h3>{text.staff}</h3><form onSubmit={createStaff}><input aria-label={text.employee} value={staffForm.employeeCode} onChange={(event) => setStaffForm({ ...staffForm, employeeCode: event.target.value })} placeholder={text.employee} required /><input aria-label={text.display} value={staffForm.displayName} onChange={(event) => setStaffForm({ ...staffForm, displayName: event.target.value })} placeholder={text.display} required /><input aria-label={text.email} type="email" value={staffForm.workEmail} onChange={(event) => setStaffForm({ ...staffForm, workEmail: event.target.value })} placeholder={text.email} required /><input aria-label={text.position} value={staffForm.position} onChange={(event) => setStaffForm({ ...staffForm, position: event.target.value })} placeholder={text.position} required /><input aria-label={text.capacity} type="number" min="1" max="100" value={staffForm.capacity} onChange={(event) => setStaffForm({ ...staffForm, capacity: event.target.value })} placeholder={text.capacity} required /><button type="submit">{text.create}</button></form>{staff.map((person) => <article key={person.staffId}><strong>{person.employeeCode}</strong> — {person.displayName} ({person.employmentState}, {person.activeWorkload}/{person.capacity})<button type="button" onClick={() => void editStaff(person)}>{text.save}</button></article>)}</div></div></section>;
}
